Improve OpenStack integration documentation
EGI-Federation/documentation pull request #190
Opened 2021-02-26 15:42 UTC by enolfc

# Summary

---

**Related issue :**

2021-02-26 15:45 UTC, gwarf approved these changes
LGTM

2021-02-26 22:20 UTC, enolfc commented
> LGTM

You are fast... I plan to add some more stuff here :)

2021-03-18 12:30 UTC, enolfc commented
@gwarf  can you take another look?

2021-03-18 13:33 UTC, gwarf requested changes
Thanks!
Added a few suggestions, please check if they make sense.

2021-03-18 13:33 UTC, gwarf commented on content/en/providers/cloud-compute/openstack/_index.md
> +Packages for gridsite can be obtained from [CMD](https://repository.egi.eu/sw/production/cmd-os/1/).
```suggestion
Packages for gridsite can be obtained from [CMD repository](https://repository.egi.eu/sw/production/cmd-os/1/).
```

2021-03-18 13:33 UTC, gwarf commented on content/en/providers/cloud-compute/openstack/_index.md
> +The appliance has a cron job that will connect to the configured OpenStack
```suggestion
The appliance has a cron job that will connect to the configured OpenStack API
```

2021-03-19 09:21 UTC, gwarf approved these changes
LGTM

2021-03-19 09:21 UTC, merged