Updated Service Provider Workflow and Guidelines to include the use o…
EGI-Federation/documentation pull request #268
Opened 2021-08-03 14:25 UTC by linathedog

Updated Service Provider Workflow and Guidelines for registering services using the Federation Registry

2021-08-10 07:59 UTC, gwarf commented
Thanks @linathedog, please address the reports from the checks, you can find information about the formatting rules at https://docs.egi.eu/about/contributing/style/. Prettier may help with the formatting.

2021-08-10 08:00 UTC, gwarf requested changes
Please address the reported errors.

2021-08-23 10:59 UTC, closed without merging

2021-08-25 10:16 UTC, NicolasLiampotis commented on content/en/providers/check-in/sp/_index.md
> +credentials and register one or more redirect URIs. The client configuration
```
credentials. The client configuration
```

2021-08-25 10:16 UTC, NicolasLiampotis commented on content/en/providers/check-in/sp/_index.md
>  You need OAuth 2.0 credentials, including a client ID and client secret, to
```
You need OAuth 2.0 credentials, which typically include a client ID and client secret, to
```

2021-08-25 10:16 UTC, NicolasLiampotis commented on content/en/providers/check-in/sp/_index.md
> +reviewed by an Operator. The responsible support unit is
```
[EGI Federation Registry Portal](https://aai.egi.eu/federation). You can also use the Federation Registry portal to request the reconfiguration or deregistration of 
an existing deployed service. Service registration requests typically require approval
by an administrator. Please refer to the [Federation Registry Documentation](https://federation.rciam.grnet.gr/docs) for more information. 

The integration follows a two-step process:
```

2021-08-25 10:20 UTC, gwarf commented
Should we re-open this PR?