Add next steps after signing up in Check-in
EGI-Federation/documentation pull request #365
Opened 2021-11-17 12:43 UTC by sebastian-luna-valero

# Summary

---

**Related issue :**

2021-11-17 12:45 UTC, sebastian-luna-valero commented
Hi!

I have a question when reading https://docs.egi.eu/users/check-in/joining-virtual-organisation/

Should PERUN VOs be searchable in the "Enrollment Flows" step?

Best regards,
Sebastian

2021-11-18 16:16 UTC, gwarf commented
@vardizzo-lab , @NicolasLiampotis , @ioigoume can you please check this PR?

2021-11-18 16:41 UTC, NicolasLiampotis requested changes
Minor typo in the next steps section (VO vs VOs) - other than that LGTM - thanks!

2021-11-18 16:41 UTC, NicolasLiampotis commented on content/en/users/check-in/signup/_index.md
> +[how to join an existing Virtual Organisation (VOs)](../joining-virtual-organisation).
"how to join an existing Virtual Organisation (VO)" (without the s)

2021-11-19 08:57 UTC, gwarf commented
Thanks for the review @NicolasLiampotis 
@vardizzo-lab or @NicolasLiampotis can you also please have a look at @sebastian-luna-valero 's question in https://github.com/EGI-Federation/documentation/pull/365#issuecomment-971545259

Let me know when we can merge this PR.

2021-11-19 10:00 UTC, NicolasLiampotis commented
> I have a question when reading https://docs.egi.eu/users/check-in/joining-virtual-organisation/
> 
> Should PERUN VOs be searchable in the "Enrollment Flows" step?
> 

Currently the "Enrollment flows" list only includes the VOs that are managed in COmanage. We can investigate with the Ops Portal / Perun teams how to include Perun-managed VOs

2021-11-19 10:45 UTC, gwarf commented
OK, I've logged a ticket about this in the Jira project for EGI Requirements so that it's assessed/discussed properly.
@NicolasLiampotis can you please mark this PR as approved if it's fine with you?

2021-11-19 10:54 UTC, NicolasLiampotis approved these changes
LGTM

2021-11-19 10:59 UTC, merged