Revamp documentation to better describe current AoD status
EGI-Federation/documentation pull request #377
Opened 2021-12-17 11:59 UTC by enolfc

# Summary

AoD has several changes that are not properly reflected in the documentation
- EC3 should be featured as top-level instead of cloud compute (it was not even in AoD!)
- Exoscale vouchers are not really active
- Chipster is not really now managed by FCSG

---

**Related issue :**

2022-01-10 16:00 UTC, enolfc commented
@thebe14 can you take a look at this one? It may conflict a bit with some of the work you are doing and I should adapt to that :)

2022-01-10 16:02 UTC, enolfc commented
> The FSGS is also down/no more working an admins are not answering, with @glarocca we agreed to remove it, so it would be good to also remove the related doc.

This is now gone (at least `git grep -i fsgs` does not show up anything)

2022-01-18 08:24 UTC, gwarf commented on content/en/users/getting-started/_index.md
> +can be turn into online services that can be accessed by scientist worldwide.
```suggestion
EGI offers a playground allocation for users to get access to the services and
understand how to port applications and develop new data analytics tools that
can be turn into online services that can be accessed by scientist worldwide.
```

2022-01-18 08:25 UTC, gwarf commented on content/en/users/getting-started/_index.md
> +this purpose (you can adapt to match the exact providers in your case):
```suggestion
this purpose (you should adapt to match the exact providers in your case):
```

2022-01-18 08:25 UTC, gwarf commented on content/en/users/getting-started/_index.md
> +the users\' requests before granting the access to the resources.
```suggestion
the users' requests before granting the access to the resources.
```
Should not be needed, right?

2022-01-18 08:25 UTC, gwarf commented on content/en/users/getting-started/_index.md
> +1. Login to the [EGI Marketplace](https://marketplace.egi.eu) with the
```suggestion
1. Log into the [EGI Marketplace](https://marketplace.egi.eu) with the
```

2022-01-18 08:27 UTC, gwarf requested changes
Thanks, LGTM, but added some small fixes to be included before we merge.

2022-01-25 14:36 UTC, gwarf approved these changes

2022-01-25 14:40 UTC, merged