Added Perun documentation section
EGI-Federation/documentation pull request #398
Opened 2022-02-07 11:22 UTC by zlamalp

# Summary

This PR adds page about VO management in Perun in the context of EGI Check-In service. So far it was completely missing.

Right now it is a draft meant for further discussions about the content structure, placement etc.

---
**Related issue :** none

2022-02-07 11:33 UTC, gwarf commented
Thanks @zlamalp !
As this is your first contribution to this repo I will have to approve the workflow run, once they have run please address the issues reported, let me know if you need some help or find something confusing.
You can look at the contributing guide pages: https://docs.egi.eu/about/contributing/
@vardizzo-lab could you please review the integration of this documentation?

2022-02-15 12:12 UTC, zlamalp commented
Hi @gwarf, can you please approve the workflow run again? I believe I've fixed lint errors. I'd like to get new version deployed in the preview. Thank you.

2022-02-15 13:37 UTC, gwarf commented
Sure @zlamalp , just did it, thanks for the reminder.
I also update the PR with the latest changes from the main branch.

2022-02-15 14:43 UTC, gwarf commented
OK, so now all is green, thanks @zlamalp !
Please let us know when this PR will be ready for review.

2022-02-24 10:58 UTC, andrea-manzi commented
@zlamalp  i see that some links in HOW-TO sections are pointing to sections in your docs still to be completed. Maybe better to hide them for the moment?

2022-02-25 08:03 UTC, zlamalp commented
@andrea-manzi HOW-TOs, which are not ready yet are now hidden, I will re-enable them once they are ready.

2022-02-25 14:14 UTC, andrea-manzi commented
> @andrea-manzi HOW-TOs, which are not ready yet are now hidden, I will re-enable them once they are ready.

@zlamalp thanks a lot, let's wait for Valeria's review and then approve the PR

2022-02-25 14:22 UTC, gwarf commented
If we want to do things cleanly we may want to split the Check-in/COmanage specific content from https://docs.egi.eu/documentation/398/users/aai/check-in/vos/ to a sub page similar to the one proposed here for PERUN, and then add some introductory text in https://docs.egi.eu/documentation/398/users/aai/check-in/vos/ describing the various possibilities (PERUN, Check-in/COmanage and VOMS)

2022-03-07 09:12 UTC, gwarf commented
@vardizzo-lab can you please have a look?

2022-10-24 15:32 UTC, andrea-manzi commented
@vardizzo-lab what is missing to include this doc?

2022-11-29 12:53 UTC, vardizzo-lab requested changes

2022-11-29 13:22 UTC, zlamalp commented on content/en/users/aai/check-in/vos/perun/_index.md
> +  VO management trough Identity and Access management system Perun
Fixed in latest version.

2022-11-29 13:22 UTC, zlamalp commented on content/en/users/aai/check-in/vos/perun/_index.md
> +Perun is identity and access management system, and within the EGI it provides
Fixed in latest version.

2022-11-29 13:22 UTC, zlamalp commented on content/en/users/aai/check-in/vos/perun/_index.md
> +- Push mechanism for services provisioning
Features not used in EGI are removed in latest version.

2022-11-29 13:22 UTC, zlamalp commented on content/en/users/aai/check-in/vos/perun/_index.md
> +- Service accounts which can be associated with owners and used for API usage
Features not used in EGI are removed in latest version.

2022-11-29 13:22 UTC, zlamalp commented on content/en/users/aai/check-in/vos/perun/_index.md
> +and not through EGI Check-In proxy.
Part about personal certificates moved to FAQ.

2022-12-01 08:35 UTC, zlamalp commented
Can someone please approve the build/check workflow so it gets deployed for the preview? Thank you.

2022-12-01 08:53 UTC, gwarf commented
Sure it's done, I overlooked this.
Once this PR will have been merged, the following ones will run the workflow automatically. :)

2023-01-19 10:24 UTC, vardizzo-lab approved these changes

2023-01-20 15:14 UTC, merged