[Check-in] Add guide for "EGI Check-in Token Portal"
EGI-Federation/documentation pull request #446
Opened 2022-05-13 10:50 UTC by nikosev

# Summary

Add "EGI Check-in Token Portal" guide in the new section "Users"<"Authentication & Authorization"<"EGI Check-in"<"Obtaining Tokens".
Also, all the references to EGI Fedcloud Token Portal have been fixed

2022-05-13 13:14 UTC, gwarf commented
Dear @vardizzo-lab please review and let us know when this PR can be merged, the preview will be soon available at https://docs.egi.eu/documentation/446

2022-05-18 08:15 UTC, vardizzo-lab requested changes

2022-05-18 08:15 UTC, vardizzo-lab commented on content/en/users/aai/check-in/obtaining-tokens/token-portal/_index.md
> +the steps bellow:
below.

2022-05-18 08:15 UTC, vardizzo-lab commented on content/en/users/aai/check-in/obtaining-tokens/token-portal/_index.md
> +follow the steps bellow:
below

2022-05-18 08:47 UTC, nikosev commented on content/en/users/aai/check-in/obtaining-tokens/token-portal/_index.md
> +the steps bellow:
typo fixed

2022-05-18 08:47 UTC, nikosev commented on content/en/users/aai/check-in/obtaining-tokens/token-portal/_index.md
> +follow the steps bellow:
typo fixed

2022-05-18 08:52 UTC, vardizzo-lab approved these changes

2022-05-18 09:46 UTC, gwarf approved these changes
LGTM

2022-05-18 09:47 UTC, merged