[Check-in] Add `client_secret` to Device Authorization Request
EGI-Federation/documentation pull request #490
Opened 2022-08-24 13:45 UTC by nikosev

# Summary

This PR adds the `client_secret` parameter to the examples of the Device Authorization Requests.

2022-08-25 08:29 UTC, NicolasLiampotis commented on content/en/providers/check-in/sp/_index.md
> +If you are using the Device Code grant, please make sure that the
If you are using a confidential client with the Device Code grant

2022-08-26 10:13 UTC, vardizzo-lab requested changes
This is the new EGI policies link: 
https://confluence.egi.eu/display/EGIPP 
Could you correct it please?

2022-08-30 07:59 UTC, gwarf commented
> This is the new EGI policies link: https://confluence.egi.eu/display/EGIPP Could you correct it please?

https://go.egi.eu/policies-and-procedures is the link that is expected to be used, we would update it later in case it would be changed.
@nikosev please revert back to this one.

2022-08-30 09:39 UTC, gwarf commented on content/en/providers/check-in/sp/_index.md
>     [GÉANT Data Protection Code of Conduct](https://wiki.refeds.org/display/CODE/Data+Protection+Code+of+Conduct+Home)
```suggestion
   [REFEDS Data Protection Code of Conduct](https://wiki.refeds.org/display/CODE/Data+Protection+Code+of+Conduct+Home)
```

2022-08-30 09:39 UTC, gwarf approved these changes
LGTM

2022-08-30 09:58 UTC, gwarf commented
@vardizzo-lab is it fine with you to merge it like this? Any other comment?

2022-09-02 08:42 UTC, vardizzo-lab approved these changes

2022-09-02 09:32 UTC, merged