Improve env documentation
EGI-Federation/documentation pull request #537
Opened 2022-10-31 09:27 UTC by enolfc

# Summary

---

**Related issue :**

2022-11-02 16:11 UTC, sebastian-luna-valero approved these changes
Thanks!

2022-11-16 16:10 UTC, gwarf commented
@enolfc is this PR waiting as draft on something specific?

2022-12-14 16:01 UTC, sebastian-luna-valero approved these changes
Minor comments below, thanks!

2022-12-14 16:01 UTC, sebastian-luna-valero commented on content/en/users/dev-env/replay/_index.md
> +[Replay JupyterHub home](https://replay.notebooks.egi.eu/hub/hub/home):
Is the double `/hub/hub` correct?

```suggestion
[Replay JupyterHub home](https://replay.notebooks.egi.eu/hub/home):
```

2022-12-15 08:15 UTC, gwarf approved these changes
LGTM, once all suggestions will have been addressed and the service will be in a good shape (certificate and so on)

2022-12-15 11:05 UTC, enolfc commented on content/en/users/dev-env/replay/_index.md
> +[Replay JupyterHub home](https://replay.notebooks.egi.eu/hub/hub/home):
True!

2023-01-06 16:12 UTC, gwarf requested changes
The certificate for the service is not valid and should be replaced before this PR can be merged.

2023-02-03 09:00 UTC, enolfc commented
> The certificate for the service is not valid and should be replaced before this PR can be merged.

replay hostname now in place. binder redirects to replay also.

2023-02-03 09:05 UTC, gwarf commented on content/en/users/dev-env/replay/_index.md
>  shown in the screenshot below, you can copy the URL shown when the building is
@enolfc, is this something you want to address before merging, or should we merge like this?

2023-02-03 09:19 UTC, gwarf approved these changes

2023-02-06 12:44 UTC, enolfc commented on content/en/users/dev-env/replay/_index.md
>  shown in the screenshot below, you can copy the URL shown when the building is
Image is now updated

2023-02-06 12:59 UTC, merged