[Check-in] Add section for the Logout Endpoint
EGI-Federation/documentation pull request #549
Opened 2022-11-17 09:09 UTC by nikosev

# Summary

This PR introduces the following changes:

- Add section for Logout Endpoint
- Fix case of OIDC terminology
- Update instruction of creating SAML SP metadata
- Add section for Redirect URIs
- Add section for UserInfo Endpoint
- Add section for Introspection Endpoint
- Fix notes refering to the endpoints table
- Move flow descriptions from `Endpoints` to `Grant Types` section
- Make duplicate headers unique in order to use them in links

2022-11-21 16:26 UTC, NicolasLiampotis approved these changes
LGTM

2022-11-23 14:10 UTC, vardizzo-lab approved these changes

2022-11-24 08:58 UTC, gwarf approved these changes
LGTM, did some small fixes on formatting of excertps.

2022-11-24 08:58 UTC, gwarf commented on content/en/providers/check-in/sp/_index.md
> +  -H "Authorization: Bearer ${ACCESS_TOKEN}" | python -m json.tool;
```suggestion
$ curl -X GET ${USERINFO_ENDPOINT}?
    -H "Content-type: application/json"
    -H "Authorization: Bearer ${ACCESS_TOKEN}" | python -m json.tool;
```

2022-11-24 08:58 UTC, gwarf commented on content/en/providers/check-in/sp/_index.md
> +  -d "token=${ACCESS_TOKEN}" | python -m json.tool;
```suggestion
$ curl -X POST "${INTROSPECTION_ENDPOINT}" \
    -u "${CLIENT_ID}":"${CLIENT_SECRET}" \
    -H "Content-Type: application/x-www-form-urlencoded" \
    -d "token=${ACCESS_TOKEN}" | python -m json.tool;
```

2022-11-24 08:58 UTC, gwarf commented on content/en/providers/check-in/sp/_index.md
> +  id_token_hint=${ID_TOKEN}
```suggestion
$ curl -X GET "${LOGOUT_ENDPOINT}?id_token_hint=${ID_TOKEN}"
```

2022-11-24 08:58 UTC, gwarf commented on content/en/providers/check-in/sp/_index.md
> +  client_id=${CLIENT_ID}
```suggestion
$ curl -X GET "${LOGOUT_ENDPOINT}post_logout_redirect_uri=${POST_LOGOUT_REDIRECT_URI}&client_id=${CLIENT_ID}"
```

2022-11-24 09:00 UTC, gwarf commented
@nikosev please confirm the changes I made are fine and I will merge, thanks!

2022-11-24 09:22 UTC, nikosev commented
Hi @gwarf !
I thought that the dollar sign (`$`) in front of the commands should be placed when the command is followed by the output of the command. Since the curl commands are now followed by their output, I didn't include the dollar sign.
If we need to add the dollar sign to all commands, then I need to update all the commands in the SP guide.

Also, the indentation of all the curl commands is set to 2 spaces. Should I update it to 4 spaces?

2022-11-24 13:33 UTC, gwarf commented
Hi, so yes, we agreed to use the prompt sign on all commands, to have a coherent usage.
We have some info on https://docs.egi.eu/about/contributing/style/#basic-rules and https://docs.egi.eu/about/contributing/shortcodes/#code-or-shell-snippets.

So for the indentation of the commands, basically they should always be two spaces from the parent/reference. Here there was the need to increment them due to adding the `$ ` prompt, so that the second line is properly padded.

2022-11-24 14:21 UTC, gwarf requested changes
Looks good, thanks!
But please review/update shell excerpts.

2022-11-24 16:41 UTC, nikosev commented
@gwarf I have made some changes based on our discussion. If there is anything that needs improvement, please let me know.

2022-11-24 16:43 UTC, nikosev commented on content/en/providers/check-in/sp/_index.md
> +```shell
I converted the syntax highlighter to `http`. I wanted to copy the code block as it is in the [OpenID Connect core specification](https://openid.net/specs/openid-connect-core-1_0.html#AuthResponse)

2022-11-25 08:38 UTC, gwarf commented on content/en/providers/check-in/sp/_index.md
> +OpenID Connect Services MUST pre-register one or more Redirection URI(s) to
```suggestion
OpenID Connect Services **MUST** pre-register one or more Redirection URI(s) to
```

2022-11-25 08:39 UTC, gwarf commented on content/en/providers/check-in/sp/_index.md
> +Comparison). Redirection URIs MUST use the schemata defined in Section 3.1.2.1
```suggestion
Comparison). Redirection URIs **MUST** use the schemata defined in Section 3.1.2.1
```

2022-11-25 08:39 UTC, gwarf commented on content/en/providers/check-in/sp/_index.md
> +specification. Note that the Redirection URI MUST use the `https` scheme; the
```suggestion
specification. Note that the Redirection URI **MUST** use the `https` scheme; the
```

2022-11-25 08:40 UTC, gwarf commented on content/en/providers/check-in/sp/_index.md
> +If the SP supports the Single Logout profile, then its metadata MUST contain
```suggestion
If the SP supports the Single Logout profile, then its metadata **MUST** contain
```

2022-11-25 08:41 UTC, gwarf commented on content/en/providers/check-in/sp/_index.md
> +is a Confidential Client, then it MUST authenticate to the Token Endpoint using
```suggestion
is a Confidential Client, then it **MUST** authenticate to the Token Endpoint using
```

2022-11-25 08:43 UTC, gwarf approved these changes

2022-11-25 08:44 UTC, gwarf commented
Perfect, thanks a lot @nikosev, let's merge!

2022-11-25 09:06 UTC, merged