Add information about the VO property
EGI-Federation/documentation pull request #618
Opened 2023-10-17 14:10 UTC by enolfc

# Summary

---

**Related issue :**

2023-10-24 08:47 UTC, gwarf approved these changes
LGTM

2023-10-24 08:54 UTC, gwarf commented
@CatalinCondurache , please have a look

2023-10-24 08:55 UTC, sebastian-luna-valero commented
Shall we promote `egi_VO` instead as discussed in the FedCloud slack channel?

2023-10-24 09:16 UTC, sebastian-luna-valero commented
On the meeting on 24th Oct 2023 it was decided (and tested) to use `egi.VO`

2023-10-24 10:56 UTC, enolfc commented
> On the meeting on 24th Oct 2023 it was decided (and tested) to use `egi.VO`

yes needs update

2023-10-24 11:24 UTC, sebastian-luna-valero requested changes
Let's update the property name from `VO` to `egi.VO` as agreed with fedcloud providers in the fedcloud task force meeting on 24th Oct 2023.

2023-10-24 11:24 UTC, sebastian-luna-valero commented on content/en/providers/cloud-compute/openstack/vo_config.md
> +1. Set the `VO` property to the name of the VO that you are supporting:
```suggestion
1. Set the `egi.VO` property to the name of the VO that you are supporting:
```

2023-10-24 11:24 UTC, sebastian-luna-valero commented on content/en/providers/cloud-compute/openstack/vo_config.md
> +   $ openstack project set --property VO=<name of the VO> <your project>
```suggestion
   $ openstack project set --property egi.VO=<name of the VO> <your project>
```

2023-10-24 11:24 UTC, sebastian-luna-valero commented on content/en/providers/cloud-compute/openstack/vo_config.md
> +If you are correctly setting the `VO` property to your projects, the configuration will
```suggestion
If you are correctly setting the `egi.VO` property to your projects, the configuration will
```

2023-10-24 13:26 UTC, enolfc commented
@CatalinCondurache can you check this one?

2023-11-14 10:45 UTC, CatalinCondurache approved these changes
approved

2023-11-14 11:26 UTC, gwarf commented
Thanks, @CatalinCondurache.
@sebastian-luna-valero the merge is blocked by your request for changes, can you please check/confirm all is OK?

2023-11-14 11:32 UTC, sebastian-luna-valero approved these changes

2023-11-14 11:42 UTC, merged